p8105_hw3_yw4664
================
Yijun Wang
2025-10-07

## Problem 1

### Loading Libraries

``` r
library(tidyverse)

library(janitor)

library(knitr)

library(ggplot2)

library(p8105.datasets)

data("instacart")
```

### 1. Short description of the dataset

``` r
nrow(instacart); ncol(instacart)
```

    ## [1] 1384617

    ## [1] 15

``` r
glimpse(instacart)
```

    ## Rows: 1,384,617
    ## Columns: 15
    ## $ order_id               <int> 1, 1, 1, 1, 1, 1, 1, 1, 36, 36, 36, 36, 36, 36,…
    ## $ product_id             <int> 49302, 11109, 10246, 49683, 43633, 13176, 47209…
    ## $ add_to_cart_order      <int> 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,…
    ## $ reordered              <int> 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,…
    ## $ user_id                <int> 112108, 112108, 112108, 112108, 112108, 112108,…
    ## $ eval_set               <chr> "train", "train", "train", "train", "train", "t…
    ## $ order_number           <int> 4, 4, 4, 4, 4, 4, 4, 4, 23, 23, 23, 23, 23, 23,…
    ## $ order_dow              <int> 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6,…
    ## $ order_hour_of_day      <int> 10, 10, 10, 10, 10, 10, 10, 10, 18, 18, 18, 18,…
    ## $ days_since_prior_order <int> 9, 9, 9, 9, 9, 9, 9, 9, 30, 30, 30, 30, 30, 30,…
    ## $ product_name           <chr> "Bulgarian Yogurt", "Organic 4% Milk Fat Whole …
    ## $ aisle_id               <int> 120, 108, 83, 83, 95, 24, 24, 21, 2, 115, 53, 1…
    ## $ department_id          <int> 16, 16, 4, 4, 15, 4, 4, 16, 16, 7, 16, 4, 16, 2…
    ## $ aisle                  <chr> "yogurt", "other creams cheeses", "fresh vegeta…
    ## $ department             <chr> "dairy eggs", "dairy eggs", "produce", "produce…

``` r
sample_n(instacart, 5)
```

    ## # A tibble: 5 × 15
    ##   order_id product_id add_to_cart_order reordered user_id eval_set order_number
    ##      <int>      <int>             <int>     <int>   <int> <chr>           <int>
    ## 1  2364597      49235                20         1  178945 train              13
    ## 2  3384237      13166                 1         1   82244 train               7
    ## 3  3256159      16281                 1         1  184810 train              49
    ## 4  1917018      19895                17         1  107745 train              35
    ## 5   943055      20955                 8         0  190673 train               5
    ## # ℹ 8 more variables: order_dow <int>, order_hour_of_day <int>,
    ## #   days_since_prior_order <int>, product_name <chr>, aisle_id <int>,
    ## #   department_id <int>, aisle <chr>, department <chr>

The instacart dataset has 1,384,617 rows and 15 variables. Every row is
a product added to an order.

Key variables include the info (order_id, user_id, order_number), timing
(order_dow 0–6, order_hour_of_day 0–23, days_since_prior_order), product
data (product_id, product_name, aisle_id/aisle,
department_id/department), and cart related info (add_to_cart_order,
reordered).

For example, there’s an order_id = 1 (user 112108’s 4th order), placed
on day 4 at 10:00, contains 8 items such as Bulgarian Yogurt and several
fresh vegetables, with some marked as reordered = 1.

### 2. How many aisles are there, and which aisles are the most items ordered from?

``` r
n_aisles <- n_distinct(instacart$aisle)
n_aisles
```

    ## [1] 134

``` r
aisle_counts <- instacart |> 
  count(aisle, sort = TRUE)

head(aisle_counts, 10) |> 
  kable(col.names = c("Aisle", "Number of items ordered"))
```

| Aisle                         | Number of items ordered |
|:------------------------------|------------------------:|
| fresh vegetables              |                  150609 |
| fresh fruits                  |                  150473 |
| packaged vegetables fruits    |                   78493 |
| yogurt                        |                   55240 |
| packaged cheese               |                   41699 |
| water seltzer sparkling water |                   36617 |
| milk                          |                   32644 |
| chips pretzels                |                   31269 |
| soy lactosefree               |                   26240 |
| bread                         |                   23635 |

There are `134` aisles; the top 3 largest are the fresh vegetables,
fresh fruits and packaged vegetables fruits aisles.

### 3. Plot showing the number of items ordered in each aisle

``` r
aisle_counts |> 
  
  filter(n > 10000) |>
  
  mutate(aisle = fct_reorder(aisle, n)) |>
  
  ggplot(aes(x = aisle, y = n)) +
  
  geom_col() +
  
  coord_flip() +
  
  labs(x = NULL, y = "Number of items ordered",
       title = "Instacart orders by aisle (over 10000 orders)") +
  
  theme_minimal(base_size = 12)
```

![](p8105_hw3_yw4664_files/figure-gfm/unnamed-chunk-4-1.png)<!-- -->

### 4. Table showing the three most popular items in each of the aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”

``` r
top3_table <- instacart |>
  
  filter(aisle %in% c("baking ingredients",
                      "dog food care",
                      "packaged vegetables fruits")) |>
  
  count(aisle, product_name, sort = TRUE) |>
  
  group_by(aisle) |>
  
  slice_max(n, n = 3, with_ties = FALSE) |>
  
  ungroup() |>
  
  arrange(aisle, desc(n))

kable(
  top3_table,
  format = "pipe",
  col.names = c("Aisle", "Product", "Times ordered"),
  caption = "Top 3 products in three aisles",
  align = c("l","l","c")
)
```

| Aisle | Product | Times ordered |
|:---|:---|:--:|
| baking ingredients | Light Brown Sugar | 499 |
| baking ingredients | Pure Baking Soda | 387 |
| baking ingredients | Cane Sugar | 336 |
| dog food care | Snack Sticks Chicken & Rice Recipe Dog Treats | 30 |
| dog food care | Organix Chicken & Brown Rice Recipe | 28 |
| dog food care | Small Dog Biscuits | 26 |
| packaged vegetables fruits | Organic Baby Spinach | 9784 |
| packaged vegetables fruits | Organic Raspberries | 5546 |
| packaged vegetables fruits | Organic Blueberries | 4966 |

Top 3 products in three aisles

### 5. Table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week

``` r
days <- c("Sun","Mon","Tue","Wed","Thu","Fri","Sat")

mean_hour_tbl <- instacart |>
  filter(product_name %in% c("Pink Lady Apples", "Coffee Ice Cream")) |>
  
  mutate(day = factor(order_dow, levels = 0:6, labels = days)) |>
  
  group_by(product_name, day) |>
  
  summarize(mean_hour = mean(order_hour_of_day), .groups = "drop") |>
  
  mutate(mean_hour = round(mean_hour, 2)) |>
  
  pivot_wider(names_from = day, values_from = mean_hour)


kable(
  mean_hour_tbl,
  format = "pipe",
  col.names = c("", days),
  caption = "Mean order hour by each day",
  align = c("l", rep("c", length(days)))
)
```

|                  |  Sun  |  Mon  |  Tue  |  Wed  |  Thu  |  Fri  |  Sat  |
|:-----------------|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| Coffee Ice Cream | 13.77 | 14.32 | 15.38 | 15.32 | 15.22 | 12.26 | 13.83 |
| Pink Lady Apples | 13.44 | 11.36 | 11.70 | 14.25 | 11.55 | 12.78 | 11.94 |

Mean order hour by each day
